### ISSUE TITLE
Configurable "morning" and "evening" time

### ISSUE THREAD

**Issue by probonopd** [RaimondB/node-red-contrib-daylight-rgbw#148]
Thanks for this very useful node.

Would it be possible to optionally set a fixed desired "morning" and "evening" time (independently of sunrise and sunset), and a desired fade duration?

For example, I want to transition from "daytime light" to "evening light"  at 10 PM, and I want the transition to happen gradually over a 2-hour time period (that is, the transition needs to begin at 8 pm so that it is complete by 10 PM).

Can this be done?

**Comment by probonopd** [comment]
In the meantime, I solved it by using a lookup table and the `interpolate` node.

**Comment by RaimondB** [comment]
Nice that were able to solve it in this way. I'll think about a way to make this easier. Maybe in general offer a configurable color temp setting on a specific time. BTW what is the reason you don't want to follow sunrise and sunset?

**Comment by probonopd** [comment]
Well, I want to stay concentrated until bedtime, and bedtime for me is (in winter time) later than sunset. In the meantime I have solved this as posted above, so I guess what I need is outside of the scope of this node (which is great btw!). Thank you.
